export type AssetView = "main" | "full_body" | "front" | "side" | "back" | "half_body" | "face" | "state" | "turnaround";
export type ImageReference = { key: string; candidate_id?: string; asset_id?: string; url?: string; fingerprint?: string; source?: string; parent_revision?: string; confirmed?: boolean; use?: string };
export type Location = { id: string; name: string; description: string; landmarks?: string; lighting?: string; palette?: string; spatial_notes?: string; states?: Record<string, string> };
export type LocationState = { version: number; revision: string; location: Location; image?: ImageReference; states?: Record<string, ImageReference>; confirmed: boolean; checks?: Record<string, boolean>; notes?: string };
export type VideoInput = { mode: "first_frame" | "first_last_frame" | "references" | "text"; resolution?: "480P" | "768P" | "1080P" | "2K" | "4K" | null; first_frame_asset_id?: string; last_frame_asset_id?: string; references: { kind: "image" | "video" | "audio"; asset_id: string; purpose: string }[]; sound_strategy: "post_audio" | "model_audio"; use_context_ir?: boolean; prompt?: string };
export type ShotReview = { status: "accepted" | "issues" | "pending"; checks: Record<string, boolean>; notes: string; issues?: { category: string; note: string }[]; stale?: boolean; fingerprint?: string };
export type Persona = {
  role_kind?: "speaking" | "background";
  identity_traits?: string;
  name: string;
  identity: string;
  age: string;
  personality: string;
  background: string;
  motivation: string;
  relationships: string;
  arc: string;
  speech: string;
  appearance: string;
  build: string;
  hair: string;
  features: string;
  clothing: string;
  accessories: string;
  image_prompt: string;
  voice_description: string;
  voice_prompt: string;
  base_speed: number;
  voice_mode?: "stable" | "expressive";
  base_pitch?: number;
  variants: Record<string, string>;
};
export type Plan = {
  title: string;
  synopsis: string;
  theme: string;
  beats: string[];
  ending: string;
  duration: number;
  scene_count?: number;
  fixed_scene_count?: boolean;
  ratio: string;
  style: string;
  characters: Persona[];
  locations: Location[];
};
export type Line = {
  id: string;
  speaker_id: string | null;
  delivery?: "on_screen" | "off_screen";
  continues_from?: string | null;
  text: string;
  emotion: string;
  speed: number;
  pause_after: number;
};
export type Shot = {
  beat_indices?: number[];
  offscreen_cast?: Record<string, string>;
  purpose?: string;
  start_state?: string;
  end_state?: string;
  action_steps?: { id: string; start_sec: number; end_sec: number; description: string; trigger_line_id?: string | null; trigger_sec?: number | null }[];
  spatial_relations?: Record<string, string>;
  continuity_from?: string | null;
  continuity_requirements?: string;
  location_revision?: string | null;
  location_state?: string;
  character_views?: Record<string, string>;
  first_frame_asset_id?: string;
  last_frame_asset_id?: string;
  subtitle_cues?: { id: string; line_id?: string | null; start_sec: number; end_sec: number; text: string }[];
  subtitles_calibrated?: boolean;
  video_input?: VideoInput;
  title: string;
  cast: Record<string, string>;
  variants: Record<string, string>;
  location_id: string;
  location_description: string;
  action: string;
  expression: string;
  composition: string;
  shot_type: string;
  camera_angle: string;
  camera_move: string;
  duration: number;
  image_prompt: string;
  lines: Line[];
  narration: Line[];
  sound_notes: string;
  audio_order?: string[];
  sound_effects?: { asset_id: string; start_sec: number; volume: number }[];
};
export type CharacterState = {
  version: number;
  revision: string;
  persona: Persona;
  confirmed: boolean;
  image?: ImageReference & { turnaround?: { key?: string; asset_id?: string; url?: string } };
  views?: Record<string, ImageReference>;
  visual_checks?: { checks: Record<string, boolean>; notes: string; image_fingerprint: string; candidate_id?: string };
  voice?: {
    voice_id: string;
    url?: string;
    key: string;
    mode: string;
    model?: string;
    generation_model?: string;
    reference?: {
      key: string;
      asset_id: string;
      duration_ms: number;
      sha256?: string;
      origin?: string;
      url?: string;
    };
    candidate_id?: string;
  };
  voice_reference?: {
    key: string;
    url: string;
    duration_ms: number;
    filename: string;
  };
  references?: Record<string, unknown>;
};
export type SceneState = {
  version: number;
  revision: string;
  edit?: { in_sec: number; out_sec: number; take: string };
  shot?: Shot;
  review?: ShotReview;
  review_current?: boolean;
  needs_binding?: boolean;
  legacy_dialogue?: string;
  legacy_narration?: string;
  image?: { candidate_id: string; logs: unknown[] };
  audio?: { duration_ms: number; candidate_id: string };
  video?: { key?: string; url?: string; task_id?: string; take?: string; parent_task_id?: string; source_task_id?: string; post_processing?: unknown[]; [key: string]: unknown };
  video_takes?: { key?: string; url?: string; [key: string]: unknown }[];
};
export type ProjectState = {
  production_segments?: { id: string; scene_ids: string[]; shot_ranges: { scene_id: string; start_sec: number; end_sec: number }[] }[];
  version: number;
  revision: string;
  locations?: Record<string, LocationState>;
  preview_confirmation?: { export_job_id: string; notes?: string; stale?: boolean };
  plan: Plan | null;
  plan_draft?: Plan | null;
  confirmed_plan?: Plan | null;
  plan_confirmed: boolean;
  cast_confirmed: boolean;
  shots_confirmed: boolean;
  narrator: { voice_id: string; speed: number };
};
export type Candidate = {
  id: string;
  entityId: string;
  kind: string;
  stale: boolean;
  selected?: boolean;
  url: string;
  taskId?: string;
  data: {
    draft?: boolean;
    raw_text?: string;
    original_value?: unknown;
    corrections?: string[];
    validation_stage?: "schema" | "semantic";
    validation_issues?: { scene_index?: number; title?: string; code?: string; message?: string; path?: (string | number)[] | string; loc?: (string | number)[]; type?: string; msg?: string }[];
    parent_candidate_id?: string;
    source_task_id?: string;
    post_processing?: unknown[];
    reason?: string;
    duration_ms?: number;
    // Paid provider output can be retained before it passes the application schema.
    value?: Plan | Persona | { scenes: Shot[] } | { voice_ids: string[]; reason: string } | Record<string, unknown> | unknown[] | string | number | boolean | null;
    logs?: unknown[];
    reference_count?: number;
    reference_mode?: string;
    voice_id?: string;
    model?: string;
    generation_model?: string;
    reference?: { asset_id: string; duration_ms: number; origin?: string };
    mode?: string;
    segments?: {
      line: Line;
      voice_id: string;
      duration_ms: number;
      url?: string;
    }[];
    asset_id?: string;
    view?: string;
    source?: string;
    parent_revision?: string;
    package_pending?: boolean;
    turnaround?: { key?: string; asset_id?: string; url?: string };
    request: { use_reference?: boolean; variant?: string; view?: string; frame?: string; text?: string };
  };
};
